/**
 * ============================================================================
 * Sri Dwar — Certificate Generation sync (Sheet row + acknowledgement email)
 * ============================================================================
 * ✅ ADDED (2026-09-05): called from server.ts right after a certificate is
 * successfully saved in Supabase. Does two things, matching exactly what
 * every other intake form on this site already does when someone submits:
 *   1. Appends a row to a "Certificate Generation" sheet tab (created
 *      automatically on first use if it doesn't exist yet — no manual
 *      Google Form setup needed for this).
 *   2. Sends the devotee an acknowledgement email — but ONLY if an email
 *      address was actually given (phone/email are both optional on the
 *      form; this fires silently if neither was provided, which is a
 *      normal, expected case, not an error).
 *
 * Routed through webhook.gs's single shared doPost dispatcher (`route:
 * "certificate_sync"`) — this file only defines the plain handler function
 * below, not its own doPost. See webhook.gs and certificatePhotoDrive.gs's
 * header comment for why: Apps Script shares one global function scope
 * per project, so more than one file defining doPost() would silently
 * collide.
 *
 * SETUP (just the Script Property — reuses your existing webhook
 * deployment, no new one needed):
 *   Project Settings -> Script Properties -> Add:
 *     GAS_CERTIFICATE_SYNC_SECRET = <a new, different long random string>
 *   Set the SAME value as an environment variable on Render.
 * ============================================================================
 */

const CERTIFICATE_SYNC_SHEET_NAME = "Certificate Generation";
const CERTIFICATE_SYNC_HEADERS = [
  "Timestamp", "Reference ID", "Devotee Name", "Phone", "Email",
  "Service", "Date", "City", "Deity", "Temple", "Generated By Role",
];

function _getOrCreateCertificateSyncSheet_() {
  const ss = SpreadsheetApp.getActiveSpreadsheet();
  let sheet = ss.getSheetByName(CERTIFICATE_SYNC_SHEET_NAME);
  if (!sheet) {
    sheet = ss.insertSheet(CERTIFICATE_SYNC_SHEET_NAME);
    sheet.appendRow(CERTIFICATE_SYNC_HEADERS);
    sheet.getRange(1, 1, 1, CERTIFICATE_SYNC_HEADERS.length).setFontWeight("bold");
  }
  return sheet;
}

function _handleCertificateGenerationSync_(body) {
  try {
    const {
      secret, refId, devoteeName, phone, email, serviceType,
      pujaDate, city, deity, temple, generatedByRole,
    } = body;

    const configuredSecret = PropertiesService.getScriptProperties().getProperty("GAS_CERTIFICATE_SYNC_SECRET");
    if (!configuredSecret || secret !== configuredSecret) {
      return { error: "Unauthorized." };
    }
    if (!refId || !devoteeName) {
      return { error: "Missing required fields." };
    }

    // 1. Sheet row — always, regardless of whether contact details exist.
    const sheet = _getOrCreateCertificateSyncSheet_();
    sheet.appendRow([
      new Date(), refId, devoteeName, phone || "", email || "",
      serviceType || "", pujaDate || "", city || "", deity || "", temple || "",
      generatedByRole || "",
    ]);

    // 2. Acknowledgement email — same choke point (sendBrandedEmail_) and
    // same builder pattern (buildAcknowledgementEmail_) every other
    // acknowledgement on this site already uses, so it behaves exactly
    // like every other one: same dedupe log, same bounce/blacklist
    // handling, same retry-tolerant banner fetch. Silently skipped (not
    // an error) if no email was given — phone/email are optional, and a
    // devotee choosing to give neither is a normal case.
    let emailSent = false;
    if (email) {
      const built = buildAcknowledgementEmail_({
        name: devoteeName,
        formLabel: "Sacred Certificate Generated",
        refId: refId,
      });
      emailSent = sendBrandedEmail_({
        to: email,
        subject: `Your Sri Dwar Blessing Certificate — Ref ${refId}`,
        html: built.html,
        refId: refId,
        emailType: "certificate_generation_ack",
        inlineImages: built.inlineImages,
      });
    }

    return { ok: true, emailSent: emailSent };
  } catch (err) {
    logError_("certificate_generation_sync", String(err));
    return { error: "Sync failed: " + err };
  }
}

// ✅ ADDED (2026-09-05): "Share This Certificate via Email" — sends the
// finished certificate PNG (rendered client-side, same image the Print/
// Download PNG buttons use) as an attachment to a devotee's email, on
// request, at any time after the certificate was created — separate from
// the automatic acknowledgement email above, which only fires once, at
// creation. Reuses the same sendBrandedEmail_ choke point as everything
// else in this project.
function _handleShareCertificateEmail_(body) {
  try {
    const { secret, to, refId, devoteeName, base64Png } = body;

    const configuredSecret = PropertiesService.getScriptProperties().getProperty("GAS_CERTIFICATE_SYNC_SECRET");
    if (!configuredSecret || secret !== configuredSecret) {
      return { error: "Unauthorized." };
    }
    if (!to || !refId || !base64Png) {
      return { error: "Missing required fields." };
    }

    const pngBytes = Utilities.base64Decode(base64Png);
    const pngBlob = Utilities.newBlob(pngBytes, "image/png", `Sri-Dwar-Certificate-${refId}.png`);

    const html = `
      <div style="max-width:470px;margin:0 auto;font-family:Georgia,'Times New Roman',serif;color:#e8f0ee;text-align:center;">
        <p style="font-size:20px;color:#2b1806;font-weight:bold;">Jai Jagannath, ${_escapeHtml_(devoteeName || "Devotee")}! 🙏</p>
        <p style="font-size:14px;color:#3a2812;">Your Sri Dwar Blessing Certificate is attached to this email — Reference: <b>${_escapeHtml_(refId)}</b>.</p>
      </div>`;

    const sent = sendBrandedEmail_({
      to: to,
      subject: `Your Sri Dwar Blessing Certificate — Ref ${refId}`,
      html: html,
      // ✅ FIX: sendBrandedEmail_'s dedupe is a PERMANENT (refId, emailType)
      // pair — using the real refId here would mean only the FIRST ever
      // "share via email" request for a given certificate actually sends;
      // every subsequent request (which is the entire point of a re-
      // shareable button) would be silently swallowed by the dedupe log.
      // A per-request nonce keeps the real refId in the subject/body for
      // the devotee, while giving each individual share attempt its own
      // dedupe identity.
      refId: `${refId}-share-${Date.now()}`,
      emailType: "certificate_share_on_request",
      attachments: [pngBlob],
    });

    return { ok: true, sent: sent };
  } catch (err) {
    logError_("certificate_share_email", String(err));
    return { error: "Share failed: " + err };
  }
}

